import type { HeadlessReferenceContent, IndexedContentItem } from 'types/apis';
import type { ApiListResponse, ApiResponse } from 'types/apis/ApiResponse';
import type { HeadlessFileUpload } from 'types/apis/HeadlessFileUpload';

/**
 * Journey interface
 * Auto-generated from Schema: Journey
 */
export interface IJourney {
  _id: string;
  journey_code?: string;
  request_title?: string;
  customer_id?: string;
  idx_customer_id?: IndexedContentItem;
  owner_user?: any;
  site_address?: string;
  serviceTypeId?: string;
  idx_serviceTypeId?: IndexedContentItem;
  priority?: JourneyPriorityEnum;
  go_no_go_status?: JourneyGoNoGoStatusEnum;
  sla_status?: JourneySlaStatusEnum;
  portal_publish_status?: JourneyPortalPublishStatusEnum;
  source_channel?: JourneySourceChannelEnum;
  survey_status?: JourneySurveyStatusEnum;
  quote_status?: JourneyQuoteStatusEnum;
  project_status?: JourneyProjectStatusEnum;
  current_step?: JourneyCurrentStepEnum;
  request_description?: string;
  portal_token?: string;
  last_activity_at?: string | Date;
  latest_site_report_at?: string | Date;
  supervisor_name?: string;
  blocked_task_count?: number;
  progress_pct?: number;
  stock_risk_summary?: string;
  procurement_alert_count?: number;
  material_need_status?: JourneyMaterialNeedStatusEnum;
  key_material_summary?: string;
  asset_need_summary?: string;
  last_payment_note?: string;
  outstanding_amount?: number;
  latest_thread_status?: string;
  thread_count?: number;
  next_milestone_name?: string;
  latest_thread_context?: string;
  milestone_count?: number;
  total_contract_value?: number;
  unread_thread_count?: number;
  collected_amount?: number;
  next_milestone_due?: string | Date;
  published_step_count?: number;
  missing_document_count?: number;
  document_count?: number;
  sales_pipeline_id?: string;
  idx_sales_pipeline_id?: IndexedContentItem;
  sales_stage_id?: string;
  idx_sales_stage_id?: IndexedContentItem;
  sale_users?: any;
  supervisor_users?: any;
  technical_users?: any;
  duplicate_customer_id?: string;
  idx_duplicate_customer_id?: IndexedContentItem;
  pm_user?: any;
  planned_start_date?: string | Date;
  planned_end_date?: string | Date;
  delivery_note?: string;
  latest_project_settlement_id?: string;
  idx_latest_project_settlement_id?: IndexedContentItem;
  latest_closeout_package_id?: string;
  idx_latest_closeout_package_id?: IndexedContentItem;
  customer_full_name?: string;
  customer_phone?: string;
  customer_email?: string;
  customer_address?: string;
  customer_province?: string;
  customer_ward?: string;
  journey_kind?: JourneyJourneyKindEnum;
  origin_journey_id?: string;
  idx_origin_journey_id?: IndexedContentItem;
}

export interface ICreateJourneyInput {
  journey_code?: string;
  request_title?: string;
  customer_id?: string;
  owner_user?: any;
  site_address?: string;
  serviceTypeId?: string;
  priority?: JourneyPriorityEnum2;
  go_no_go_status?: JourneyGoNoGoStatusEnum2;
  sla_status?: JourneySlaStatusEnum2;
  portal_publish_status?: JourneyPortalPublishStatusEnum2;
  source_channel?: JourneySourceChannelEnum2;
  survey_status?: JourneySurveyStatusEnum2;
  quote_status?: JourneyQuoteStatusEnum2;
  project_status?: JourneyProjectStatusEnum2;
  current_step?: JourneyCurrentStepEnum2;
  request_description?: string;
  portal_token?: string;
  last_activity_at?: string | Date;
  latest_site_report_at?: string | Date;
  supervisor_name?: string;
  blocked_task_count?: number;
  progress_pct?: number;
  stock_risk_summary?: string;
  procurement_alert_count?: number;
  material_need_status?: JourneyMaterialNeedStatusEnum2;
  key_material_summary?: string;
  asset_need_summary?: string;
  last_payment_note?: string;
  outstanding_amount?: number;
  latest_thread_status?: string;
  thread_count?: number;
  next_milestone_name?: string;
  latest_thread_context?: string;
  milestone_count?: number;
  total_contract_value?: number;
  unread_thread_count?: number;
  collected_amount?: number;
  next_milestone_due?: string | Date;
  published_step_count?: number;
  missing_document_count?: number;
  document_count?: number;
  sales_pipeline_id?: string;
  sales_stage_id?: string;
  sale_users?: any;
  supervisor_users?: any;
  technical_users?: any;
  duplicate_customer_id?: string;
  pm_user?: any;
  planned_start_date?: string | Date;
  planned_end_date?: string | Date;
  delivery_note?: string;
  latest_project_settlement_id?: string;
  latest_closeout_package_id?: string;
  customer_full_name?: string;
  customer_phone?: string;
  customer_email?: string;
  customer_address?: string;
  customer_province?: string;
  customer_ward?: string;
  journey_kind?: JourneyJourneyKindEnum2;
  origin_journey_id?: string;
}

export type IJourneyListResponse = ApiListResponse<IJourney>

// Union types generated from value_options
export type JourneyPriorityEnum = 'low' | 'medium' | 'high' | 'critical';
export type JourneyGoNoGoStatusEnum = 'draft' | 'go' | 'no_go' | 'on_hold' | 'pending';
export type JourneySlaStatusEnum = 'on_time' | 'at_risk' | 'overdue';
export type JourneyPortalPublishStatusEnum = 'hidden' | 'partial' | 'published';
export type JourneySourceChannelEnum = 'marketing' | 'hotline' | 'referral' | 'direct';
export type JourneySurveyStatusEnum = 'not_started' | 'scheduled' | 'in_progress' | 'completed';
export type JourneyQuoteStatusEnum = 'not_started' | 'draft' | 'sent' | 'approved';
export type JourneyProjectStatusEnum = 'not_started' | 'active' | 'completed' | 'cancelled';
export type JourneyCurrentStepEnum = 'lead_new' | 'consult_contact' | 'site_survey' | 'solution_design' | 'quotation' | 'contract' | 'execution' | 'final_acceptance' | 'payment' | 'maintenance' | 'warranty' | 'after_sales';
export type JourneyMaterialNeedStatusEnum = 'enough' | 'partial' | 'waiting';
export type JourneyJourneyKindEnum = 'main' | 'maintenance' | 'warranty';
export type JourneyPriorityEnum2 = 'low' | 'medium' | 'high' | 'critical';
export type JourneyGoNoGoStatusEnum2 = 'draft' | 'go' | 'no_go' | 'on_hold' | 'pending';
export type JourneySlaStatusEnum2 = 'on_time' | 'at_risk' | 'overdue';
export type JourneyPortalPublishStatusEnum2 = 'hidden' | 'partial' | 'published';
export type JourneySourceChannelEnum2 = 'marketing' | 'hotline' | 'referral' | 'direct';
export type JourneySurveyStatusEnum2 = 'not_started' | 'scheduled' | 'in_progress' | 'completed';
export type JourneyQuoteStatusEnum2 = 'not_started' | 'draft' | 'sent' | 'approved';
export type JourneyProjectStatusEnum2 = 'not_started' | 'active' | 'completed' | 'cancelled';
export type JourneyCurrentStepEnum2 = 'lead_new' | 'consult_contact' | 'site_survey' | 'solution_design' | 'quotation' | 'contract' | 'execution' | 'final_acceptance' | 'payment' | 'maintenance' | 'warranty' | 'after_sales';
export type JourneyMaterialNeedStatusEnum2 = 'enough' | 'partial' | 'waiting';
export type JourneyJourneyKindEnum2 = 'main' | 'maintenance' | 'warranty';
