import type { IndexedContentItem } from 'types/apis';
import type { ApiListResponse, ApiResponse } from 'types/apis/ApiResponse';
import type { HeadlessFileUpload } from 'types/apis/HeadlessFileUpload';

/**
 * PermissionDefinition interface
 * Auto-generated from Schema: PermissionDefinition
 */
export interface IPermissionDefinition {
  _id: string;
  short_name?: string;
  code?: string;
  type?: PermissionDefinitionTypeEnum;
  scope?: PermissionDefinitionScopeEnum;
  api?: string;
  schema_name?: string;
  description?: string;
  sourceKind?: PermissionDefinitionSourceKindEnum;
  declaring_module?: string;
  declaring_type?: string;
  declaring_member?: string;
  metadata_incomplete?: boolean;
  bindings?: IBindingsItem[];
  panel_description?: string;
  root_description?: string;
  isSubPermissions?: boolean;
  isManualDefined?: boolean;
  action?: IActionItem[];
  name?: string;
}

export interface IBindingsItem {
  kind?: BindingsKindEnum;
  refId?: string;
  refLabel?: string;
  refSubType?: string;
  isAutoGenerated?: boolean;
}

export interface IActionItem {
  name?: string;
  steps?: IStepsItem[];
  placement?: ActionPlacementEnum;
  trackClickBegin?: boolean;
  trackClickEnd?: boolean;
  enableDisplayCondition?: boolean;
  displayCondition?: string;
  isSubmitForm?: boolean;
  use_api_check_executable?: boolean;
  api_check_executable?: string;
  key?: string;
  className?: string;
  faIcon?: string;
  style?: string;
  data_grid?: IDataGridItem[];
}

export interface IStepsItem {
  subject?: string;
  type?: StepsTypeEnum;
  disabled?: boolean;
  setting?: any;
  is_skip_condition?: boolean;
  is_terminate_condition?: boolean;
  skip_condition?: string;
  show_confirm_message?: boolean;
  confirm_message?: string;
  confirm_type?: string;
  confirm_ok_label?: string;
  confirm_cancel_label?: string;
  show_finish_message?: boolean;
  finish_message?: string;
  finish_message_type?: string;
  terminate_condition?: string;
  show_loading?: boolean;
  loading_message?: string;
}

export interface IDataGridItem {
  x?: number;
  y?: number;
  w?: number;
  h?: number;
  static?: boolean;
  minW?: number;
  minH?: number;
  isResizable?: boolean;
  isDraggable?: boolean;
  isBounded?: boolean;
}

export interface ICreatePermissionDefinitionInput {
  short_name?: string;
  code?: string;
  type?: PermissionDefinitionTypeEnum2;
  scope?: PermissionDefinitionScopeEnum2;
  api?: string;
  schema_name?: string;
  description?: string;
  sourceKind?: PermissionDefinitionSourceKindEnum2;
  declaring_module?: string;
  declaring_type?: string;
  declaring_member?: string;
  metadata_incomplete?: boolean;
  bindings?: IBindingsItem[];
  panel_description?: string;
  root_description?: string;
  isSubPermissions?: boolean;
  isManualDefined?: boolean;
  action?: IActionItem[];
  name?: string;
}

export type IPermissionDefinitionListResponse = ApiListResponse<IPermissionDefinition>

// Union types generated from value_options
export type PermissionDefinitionTypeEnum = 'Custom' | 'Create' | 'Update' | 'Delete' | 'Import' | 'Lock' | 'View' | 'Commit' | 'Approve' | 'Publish' | 'ValueAccess';
export type PermissionDefinitionScopeEnum = 'Global' | 'Item';
export type PermissionDefinitionSourceKindEnum = 'AutoPanel' | 'AutoSchema' | 'Manual' | 'NativeApi' | 'DynamicApi' | 'System';
export type BindingsKindEnum = 'Panel' | 'Menu' | 'NativeApi' | 'DynamicApi';
export type ActionPlacementEnum = 'TOP' | 'BOTTOM' | 'EXTRA';
export type StepsTypeEnum = 'NONE' | 'POPUP' | 'REDIRECT' | 'SETQUERYPARAMETERS' | 'LOAD' | 'INSERT' | 'UPDATE' | 'UPDATE_SET' | 'UPDATE_SET_UNCONTROL' | 'DELETE' | 'CLONE' | 'DELETE_REQUEST' | 'DETAIL' | 'LOCK' | 'SYNC_DIRECTORY_TREE' | 'UNLOCK' | 'CHECKPERMISSION' | 'COMMIT' | 'CONFIRM' | 'REJECT' | 'CLOSE' | 'CLEARFORM' | 'DOWNLOAD' | 'CALL' | 'PLAYSOUND' | 'SETDATA' | 'NEWDATA' | 'MODIFYDATA' | 'SET_PANEL_DATA' | 'UPDATEUNCONTROL' | 'VALIDATEDATA' | 'LAYOUTSUBMIT' | 'EXECUTESCRIPT' | 'DELETEDRAFT' | 'CLOSEALL' | 'ASSIGN' | 'CALLASSISTANT' | 'PRINT' | 'PREVIEWHTML' | 'PREVIEWIFRAME' | 'EXPORTWORD' | 'DELETEALL' | 'SHOWCONFIRM' | 'SHOWCHATBOX' | 'RELOADLAYOUT' | 'RELOADPANEL' | 'SHOWVERSIONS' | 'ELECTRONICSIGNATURE' | 'CHECKDUPLICATE' | 'PERMISSION' | 'SHOWMESSAGE' | 'PUSHNOTIFICATION' | 'CHANGEPASSWORD' | 'IMPORT' | 'EXPORT' | 'CALLAPI' | 'CALLFUNCTION' | 'CALLPLUGIN' | 'SHOWPREVIEWDATA' | 'WAIT' | 'SOFTUPDATE' | 'SENDEMAIL' | 'PAYMENT' | 'FAKEDATA' | 'COPYTOCLIPBOARD' | 'TTS' | 'TRANSLATE';
export type PermissionDefinitionTypeEnum2 = 'Custom' | 'Create' | 'Update' | 'Delete' | 'Import' | 'Lock' | 'View' | 'Commit' | 'Approve' | 'Publish' | 'ValueAccess';
export type PermissionDefinitionScopeEnum2 = 'Global' | 'Item';
export type PermissionDefinitionSourceKindEnum2 = 'AutoPanel' | 'AutoSchema' | 'Manual' | 'NativeApi' | 'DynamicApi' | 'System';
