import { gql } from 'graphql-tag';

/**
 * Find ContentDeleted DTO with typed data
 */
export const FIND_CONTENTDELETED_DTO = gql`
  query FindContentDeletedDto($_id: String!, $custominput: Dictionary) {
    response: find_ContentDeleted_dto(_id: $_id, custominput: $custominput) {
      code
      message
      data {
        _id
        createdAt
        updatedAt
        createdBy
        updatedBy
        content_id
        deletedTime
        deleter
        sessionTime
        isLocked
        isDraft
        schema
        lockedBy
        tenantId
        ownerId
        departmentId
        orgPath
        lastVersionId
        versionId
        translate
        approvalSnapshot {
          currentVersionId
          currentState
          currentTicketId
          snapshotUpdatedAt
          finalActionType
          finalApproverUserIds
          finalDecisionNote
          finalActionAt {
            Date
            Day
            DayOfWeek
            DayOfYear
            Hour
            Kind
            Millisecond
            Microsecond
            Nanosecond
            Minute
            Month
            Second
            Ticks
            TimeOfDay {
              Ticks
              Days
              Hours
              Milliseconds
              Microseconds
              Nanoseconds
              Minutes
              Seconds
              TotalDays
              TotalHours
              TotalMilliseconds
              TotalMicroseconds
              TotalNanoseconds
              TotalMinutes
              TotalSeconds
            }
            Year
          }
          currentStageInfo
          pendingAssigneeUserIds
        }
        main_thread_id
        thread_ids
        wf_approval {
          status
          instance_id
          current_step
          progress {
            current
            total
            percent
          }
          due_at {
            Date
            Day
            DayOfWeek
            DayOfYear
            Hour
            Kind
            Millisecond
            Microsecond
            Nanosecond
            Minute
            Month
            Second
            Ticks
            TimeOfDay {
              Ticks
              Days
              Hours
              Milliseconds
              Microseconds
              Nanoseconds
              Minutes
              Seconds
              TotalDays
              TotalHours
              TotalMilliseconds
              TotalMicroseconds
              TotalNanoseconds
              TotalMinutes
              TotalSeconds
            }
            Year
          }
          priority
          last_action {
            action
            actor_user_id
            actor_name
            at
          }
          updated_at
          definition {
            id
            key
            name
            version
          }
          instance {
            id
            status
            started_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            ended_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            duration_seconds
          }
          current_step_detail {
            id
            name
            type
            index
            status
            started_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            due_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
          }
          steps {
            id
            name
            type
            order
            status
            started_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            ended_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            duration_seconds
            sla {
              due_at {
                Date
                Day
                DayOfWeek
                DayOfYear
                Hour
                Kind
                Millisecond
                Microsecond
                Nanosecond
                Minute
                Month
                Second
                Ticks
                TimeOfDay
                Year
              }
              is_overdue
            }
            assignees {
              user_id
              username
              display_name
              department_id
              department_name
            }
            actions {
              action
              actor_user_id
              actor_name
              comment
              at
            }
            jobs {
              job_id
              status
              assigned_to
              started_at {
                Date
                Day
                DayOfWeek
                DayOfYear
                Hour
                Kind
                Millisecond
                Microsecond
                Nanosecond
                Minute
                Month
                Second
                Ticks
                TimeOfDay
                Year
              }
              completed_at {
                Date
                Day
                DayOfWeek
                DayOfYear
                Hour
                Kind
                Millisecond
                Microsecond
                Nanosecond
                Minute
                Month
                Second
                Ticks
                TimeOfDay
                Year
              }
              evidence {
                attachments
                note
              }
            }
          }
          history {
            event
            step_id
            at
            actor_user_id
            actor_name
            meta
          }
        }
        customData
        isSeeding
      }
    }
  }
`;

/**
 * Query ContentDeleteds DTO list
 */
export const QUERY_CONTENTDELETEDS_DTO = gql`
  query QueryContentDeletedsDto(
    $filter: GeneralCollectionFilterInput,
    $custominput: Dictionary
  ) {
    response: query_ContentDeleteds_dto(filter: $filter, custominput: $custominput) {
      code
      message
      records
      data {
        _id
        content_id
        deletedTime
        deleter
        sessionTime
        isLocked
        isDraft
        schema
        lockedBy
        tenantId
        ownerId
        departmentId
        orgPath
        lastVersionId
        versionId
        translate
        approvalSnapshot {
          currentVersionId
          currentState
          currentTicketId
          snapshotUpdatedAt
          finalActionType
          finalApproverUserIds
          finalDecisionNote
          finalActionAt {
            Date
            Day
            DayOfWeek
            DayOfYear
            Hour
            Kind
            Millisecond
            Microsecond
            Nanosecond
            Minute
            Month
            Second
            Ticks
            TimeOfDay {
              Ticks
              Days
              Hours
              Milliseconds
              Microseconds
              Nanoseconds
              Minutes
              Seconds
              TotalDays
              TotalHours
              TotalMilliseconds
              TotalMicroseconds
              TotalNanoseconds
              TotalMinutes
              TotalSeconds
            }
            Year
          }
          currentStageInfo
          pendingAssigneeUserIds
        }
        main_thread_id
        thread_ids
        wf_approval {
          status
          instance_id
          current_step
          progress {
            current
            total
            percent
          }
          due_at {
            Date
            Day
            DayOfWeek
            DayOfYear
            Hour
            Kind
            Millisecond
            Microsecond
            Nanosecond
            Minute
            Month
            Second
            Ticks
            TimeOfDay {
              Ticks
              Days
              Hours
              Milliseconds
              Microseconds
              Nanoseconds
              Minutes
              Seconds
              TotalDays
              TotalHours
              TotalMilliseconds
              TotalMicroseconds
              TotalNanoseconds
              TotalMinutes
              TotalSeconds
            }
            Year
          }
          priority
          last_action {
            action
            actor_user_id
            actor_name
            at
          }
          updated_at
          definition {
            id
            key
            name
            version
          }
          instance {
            id
            status
            started_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            ended_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            duration_seconds
          }
          current_step_detail {
            id
            name
            type
            index
            status
            started_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            due_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
          }
          steps {
            id
            name
            type
            order
            status
            started_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            ended_at {
              Date
              Day
              DayOfWeek
              DayOfYear
              Hour
              Kind
              Millisecond
              Microsecond
              Nanosecond
              Minute
              Month
              Second
              Ticks
              TimeOfDay {
                Ticks
                Days
                Hours
                Milliseconds
                Microseconds
                Nanoseconds
                Minutes
                Seconds
                TotalDays
                TotalHours
                TotalMilliseconds
                TotalMicroseconds
                TotalNanoseconds
                TotalMinutes
                TotalSeconds
              }
              Year
            }
            duration_seconds
            sla {
              due_at {
                Date
                Day
                DayOfWeek
                DayOfYear
                Hour
                Kind
                Millisecond
                Microsecond
                Nanosecond
                Minute
                Month
                Second
                Ticks
                TimeOfDay
                Year
              }
              is_overdue
            }
            assignees {
              user_id
              username
              display_name
              department_id
              department_name
            }
            actions {
              action
              actor_user_id
              actor_name
              comment
              at
            }
            jobs {
              job_id
              status
              assigned_to
              started_at {
                Date
                Day
                DayOfWeek
                DayOfYear
                Hour
                Kind
                Millisecond
                Microsecond
                Nanosecond
                Minute
                Month
                Second
                Ticks
                TimeOfDay
                Year
              }
              completed_at {
                Date
                Day
                DayOfWeek
                DayOfYear
                Hour
                Kind
                Millisecond
                Microsecond
                Nanosecond
                Minute
                Month
                Second
                Ticks
                TimeOfDay
                Year
              }
              evidence {
                attachments
                note
              }
            }
          }
          history {
            event
            step_id
            at
            actor_user_id
            actor_name
            meta
          }
        }
        customData
        isSeeding
      }
    }
  }
`;
