import { gql } from 'graphql-tag';

/**
 * Find MenuNodeDto DTO with typed data
 */
export const FIND_MENUNODEDTO_DTO = gql`
  query FindMenuNodeDtoDto($_id: String!, $custominput: Dictionary) {
    response: find_MenuNodeDto_dto(_id: $_id, custominput: $custominput) {
      code
      message
      data {
        _id
        createdAt
        updatedAt
        createdBy
        updatedBy
        title
        url
        children {
          title
          url
          children {
            title
            url
            children {
              title
              url
              children {
                title
                url
                children
                name
                target_schema
                moduleIds
                panel_type
                url_type
                layoutId
                viewExtensionId
                requiredPermissions
                isDefault
                isHidden
                parentId
                type
                icon
                path
                absolutePath
                description
                level
                priority
                action_steps
                isRootScope
                showBadge
                badgeScript
                badgeType
                badgeColor
                id
              }
              name
              target_schema
              moduleIds
              panel_type
              url_type
              layoutId
              viewExtensionId
              requiredPermissions
              isDefault
              isHidden
              parentId
              type
              icon
              path
              absolutePath
              description
              level
              priority
              action_steps {
                subject
                type
                disabled
                setting
                is_skip_condition
                is_terminate_condition
                skip_condition
                show_confirm_message
                confirm_message
                confirm_type
                confirm_ok_label
                confirm_cancel_label
                show_finish_message
                finish_message
                finish_message_type
                terminate_condition
                show_loading
                loading_message
              }
              isRootScope
              showBadge
              badgeScript
              badgeType
              badgeColor
              id
            }
            name
            target_schema
            moduleIds
            panel_type
            url_type
            layoutId
            viewExtensionId
            requiredPermissions
            isDefault
            isHidden
            parentId
            type
            icon
            path
            absolutePath
            description
            level
            priority
            action_steps {
              subject
              type
              disabled
              setting
              is_skip_condition
              is_terminate_condition
              skip_condition
              show_confirm_message
              confirm_message
              confirm_type
              confirm_ok_label
              confirm_cancel_label
              show_finish_message
              finish_message
              finish_message_type
              terminate_condition
              show_loading
              loading_message
            }
            isRootScope
            showBadge
            badgeScript
            badgeType
            badgeColor
            id
          }
          name
          target_schema
          moduleIds
          panel_type
          url_type
          layoutId
          viewExtensionId
          requiredPermissions
          isDefault
          isHidden
          parentId
          type
          icon
          path
          absolutePath
          description
          level
          priority
          action_steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          isRootScope
          showBadge
          badgeScript
          badgeType
          badgeColor
          id
        }
        name
        target_schema
        moduleIds
        panel_type
        url_type
        layoutId
        viewExtensionId
        requiredPermissions
        isDefault
        isHidden
        parentId
        type
        icon
        path
        absolutePath
        description
        level
        priority
        action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isRootScope
        showBadge
        badgeScript
        badgeType
        badgeColor
      }
    }
  }
`;

/**
 * Query MenuNodeDtos DTO list
 */
export const QUERY_MENUNODEDTOS_DTO = gql`
  query QueryMenuNodeDtosDto(
    $filter: GeneralCollectionFilterInput,
    $custominput: Dictionary
  ) {
    response: query_MenuNodeDtos_dto(filter: $filter, custominput: $custominput) {
      code
      message
      records
      data {
        _id
        title
        url
        children {
          title
          url
          children {
            title
            url
            children {
              title
              url
              children {
                title
                url
                children
                name
                target_schema
                moduleIds
                panel_type
                url_type
                layoutId
                viewExtensionId
                requiredPermissions
                isDefault
                isHidden
                parentId
                type
                icon
                path
                absolutePath
                description
                level
                priority
                action_steps
                isRootScope
                showBadge
                badgeScript
                badgeType
                badgeColor
                id
              }
              name
              target_schema
              moduleIds
              panel_type
              url_type
              layoutId
              viewExtensionId
              requiredPermissions
              isDefault
              isHidden
              parentId
              type
              icon
              path
              absolutePath
              description
              level
              priority
              action_steps {
                subject
                type
                disabled
                setting
                is_skip_condition
                is_terminate_condition
                skip_condition
                show_confirm_message
                confirm_message
                confirm_type
                confirm_ok_label
                confirm_cancel_label
                show_finish_message
                finish_message
                finish_message_type
                terminate_condition
                show_loading
                loading_message
              }
              isRootScope
              showBadge
              badgeScript
              badgeType
              badgeColor
              id
            }
            name
            target_schema
            moduleIds
            panel_type
            url_type
            layoutId
            viewExtensionId
            requiredPermissions
            isDefault
            isHidden
            parentId
            type
            icon
            path
            absolutePath
            description
            level
            priority
            action_steps {
              subject
              type
              disabled
              setting
              is_skip_condition
              is_terminate_condition
              skip_condition
              show_confirm_message
              confirm_message
              confirm_type
              confirm_ok_label
              confirm_cancel_label
              show_finish_message
              finish_message
              finish_message_type
              terminate_condition
              show_loading
              loading_message
            }
            isRootScope
            showBadge
            badgeScript
            badgeType
            badgeColor
            id
          }
          name
          target_schema
          moduleIds
          panel_type
          url_type
          layoutId
          viewExtensionId
          requiredPermissions
          isDefault
          isHidden
          parentId
          type
          icon
          path
          absolutePath
          description
          level
          priority
          action_steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          isRootScope
          showBadge
          badgeScript
          badgeType
          badgeColor
          id
        }
        name
        target_schema
        moduleIds
        panel_type
        url_type
        layoutId
        viewExtensionId
        requiredPermissions
        isDefault
        isHidden
        parentId
        type
        icon
        path
        absolutePath
        description
        level
        priority
        action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isRootScope
        showBadge
        badgeScript
        badgeType
        badgeColor
      }
    }
  }
`;
