import { gql } from 'graphql-tag';

/**
 * Find PermissionDefinition DTO with typed data
 */
export const FIND_PERMISSIONDEFINITION_DTO = gql`
  query FindPermissionDefinitionDto($_id: String!, $custominput: Dictionary) {
    response: find_PermissionDefinition_dto(_id: $_id, custominput: $custominput) {
      code
      message
      data {
        _id
        createdAt
        updatedAt
        createdBy
        updatedBy
        short_name
        code
        type
        scope
        api
        schema_name
        description
        sourceKind
        declaring_module
        declaring_type
        declaring_member
        metadata_incomplete
        bindings {
          kind
          refId
          refLabel
          refSubType
          isAutoGenerated
        }
        panel_description
        root_description
        isSubPermissions
        isManualDefined
        action {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        name
      }
    }
  }
`;

/**
 * Query PermissionDefinitions DTO list
 */
export const QUERY_PERMISSIONDEFINITIONS_DTO = gql`
  query QueryPermissionDefinitionsDto(
    $filter: GeneralCollectionFilterInput,
    $custominput: Dictionary
  ) {
    response: query_PermissionDefinitions_dto(filter: $filter, custominput: $custominput) {
      code
      message
      records
      data {
        _id
        short_name
        code
        type
        scope
        api
        schema_name
        description
        sourceKind
        declaring_module
        declaring_type
        declaring_member
        metadata_incomplete
        bindings {
          kind
          refId
          refLabel
          refSubType
          isAutoGenerated
        }
        panel_description
        root_description
        isSubPermissions
        isManualDefined
        action {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        name
      }
    }
  }
`;
