import { gql } from 'graphql-tag';

/**
 * Find ReportDashboard DTO with typed data
 */
export const FIND_REPORTDASHBOARD_DTO = gql`
  query FindReportDashboardDto($_id: String!, $custominput: Dictionary) {
    response: find_ReportDashboard_dto(_id: $_id, custominput: $custominput) {
      code
      message
      data {
        _id
        createdAt
        updatedAt
        createdBy
        updatedBy
        panelType
        tags
        filter_setting {
          items {
            id
            label
            operators
            editor
            propType
            value_options {
              value
              label
              hints
              color
              faIcon
              cssClass
              style
              tooltip
              group
              order
              disabled
              hidden
              disabledWhen
              visibleWhen
            }
            refSchemas
            suggestion_script
            has_suggestion_script
            minValue
            maxValue
            step
            defaultJsScript
            defaultValue
            set_default_value
            default_js_value
            use_as_query_only
            hide
            schema
            is_custom
          }
          mode
          position
        }
        dsId
        items {
          showPanelTitle
          reportId
          key
          name
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        header {
          key
          name
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        footer {
          key
          name
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        itemAlign
        cols
        rowHeight
        no_header
        enableBc
        actions {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        maxActiveAction
        is_custom_header
        custom_headerId
        extraAuthorizationScript
        version {
          Major
          Minor
          Build
          Revision
          MajorRevision
          MinorRevision
        }
        moduleIds
        enableBackAction
        backAction {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        description
        requiredExtraAuthorization
        allowAnonymous
        autoReload
        interval
        path
        initial_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isInvEvent
        inv_evt_second
        inv_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isDcEvent
        dc_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        use_ext_db
        ext_db_id
        name
      }
    }
  }
`;

/**
 * Query ReportDashboards DTO list
 */
export const QUERY_REPORTDASHBOARDS_DTO = gql`
  query QueryReportDashboardsDto(
    $filter: GeneralCollectionFilterInput,
    $custominput: Dictionary
  ) {
    response: query_ReportDashboards_dto(filter: $filter, custominput: $custominput) {
      code
      message
      records
      data {
        _id
        panelType
        tags
        filter_setting {
          items {
            id
            label
            operators
            editor
            propType
            value_options {
              value
              label
              hints
              color
              faIcon
              cssClass
              style
              tooltip
              group
              order
              disabled
              hidden
              disabledWhen
              visibleWhen
            }
            refSchemas
            suggestion_script
            has_suggestion_script
            minValue
            maxValue
            step
            defaultJsScript
            defaultValue
            set_default_value
            default_js_value
            use_as_query_only
            hide
            schema
            is_custom
          }
          mode
          position
        }
        dsId
        items {
          showPanelTitle
          reportId
          key
          name
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        header {
          key
          name
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        footer {
          key
          name
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        itemAlign
        cols
        rowHeight
        no_header
        enableBc
        actions {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        maxActiveAction
        is_custom_header
        custom_headerId
        extraAuthorizationScript
        version {
          Major
          Minor
          Build
          Revision
          MajorRevision
          MinorRevision
        }
        moduleIds
        enableBackAction
        backAction {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        description
        requiredExtraAuthorization
        allowAnonymous
        autoReload
        interval
        path
        initial_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isInvEvent
        inv_evt_second
        inv_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isDcEvent
        dc_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        use_ext_db
        ext_db_id
        name
      }
    }
  }
`;
