import { gql } from 'graphql-tag';

/**
 * Find Schema DTO with typed data
 */
export const FIND_SCHEMA_DTO = gql`
  query FindSchemaDto($_id: String!, $custominput: Dictionary) {
    response: find_Schema_dto(_id: $_id, custominput: $custominput) {
      code
      message
      data {
        _id
        createdAt
        updatedAt
        createdBy
        updatedBy
        panelType
        allowAI
        faIcon
        inherit_sync_schemas {
          base_schema
          inherited_props
        }
        linked_reports
        linked_documents
        linked_timeline_flows
        deleteCascade
        enable_prop_ext
        max_prop_ext
        use_update_trigger
        use_post_update_trigger
        segment_by_schema_name
        property_groups {
          name
          view_layout
          form_layout
          showLabel
          style {
            gap
            dense
            maxWidth
            alignItems
            justifyContent
            labelPosition
          }
        }
        is_system_schema
        use_saved_trigger
        use_delete_trigger
        use_authorization_trigger
        update_trigger_script
        post_update_trigger_script
        saved_trigger_script
        delete_trigger_script
        authorization_script
        disable
        is_tenant
        auto_update_if_duplicate
        auto_applychange_to_all_view
        auto_applychange_to_all_form
        prefer_view_panel_type
        formGroupType
        manualFormLayout
        defaultDetailPanelId
        defaultDetailPanelType
        not_validate_import
        not_validate_delete
        is_view
        schema_of_view
        debug
        displayOutputLog
        is_org_chart
        parentIdKey
        approval {
          enabled
          enable_approval_event
          on_approval_script
          enable_auto_mapping
          event_mappings {
            eventType
            mappings {
              propertyName
              valueExpression
            }
          }
          defaultDueAfter {
            Ticks
            Days
            Hours
            Milliseconds
            Microseconds
            Nanoseconds
            Minutes
            Seconds
            TotalDays
            TotalHours
            TotalMilliseconds
            TotalMicroseconds
            TotalNanoseconds
            TotalMinutes
            TotalSeconds
          }
        }
        conditionalGuardrails {
          name
          condition_field
          op
          condition_values
          fields
          exclude_fields
          message
          override_permission
          block_request
          apply_on_create
          when_changed_only
        }
        rls {
          rls_enabled
          rowAccessDefaults
          rowAccessRules {
            name
            applies_to {
              roles
              role_types
              positions
              departments
              current_user_department
            }
            scope
            operations {
              read
              update
              delete
            }
            extra_condition {
              field
              op
              values
            }
            message
          }
          allow_tenant_override
          tenant_override_whitelist {
            allow_override_owd
            allow_add_rules
            allow_weaken_rules
            allowed_owner_strategies
            allowed_department_strategies
            allow_client_set_owner
            allow_client_set_department
          }
          owner_strategy
          owner_payload_field
          owner_fixed_accountId
          allow_client_set_owner
          department_strategy
          department_payload_field
          department_from_field
          department_fixed_id
          allow_client_set_department
          rebuild_orgPath_on_update
          clone_keep_source_owner
          clone_keep_source_department
          access_owner_field
          access_department_field
        }
        chatboxSetting {
          enable_file_sharing
          enable_mentions
          enable_reactions
          default_visibility
          enable_comment
          enable_edit
          related_schema_policies {
            target_schema
            label
            direction
            source_prop_id
            target_prop_id
            required_permission
          }
          enable_sub_threads
          max_thread_depth
          auto_threads {
            thread_code
            thread_type
            title_template
            visibility
            singleton
            settings {
              allow_anonymous
              share_link_expiration_days
              auto_generate_share_link
              require_approval
              default_approver_role
              hide_from_external
              auto_archive_on_close
            }
          }
          allowed_thread_types
          merge_rule_setting {
            internal_view_strategy
            customer_view_strategy
            reply_target_strategy
            share_toggle_effect
          }
        }
        apis
        groupUniqueProps
        groupIndexProps {
          Capacity
          Count
          Item
        }
        controllers
        name
        keyField
        enable_log
        is_version
        is_draft
        is_private_resource
        collection
        tags
        label
        isNative
        use_extra_view_pipeline
        extra_view_pipeline
        error_message
        depended_schemas {
          targetSchema
          targetPropId
          targetPropType
          sourcePropId
          viewId
          name
        }
        delete_dependances
        update_dependances
        should_delete_dependances
        type
        no_header
        enableBc
        actions {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        maxActiveAction
        is_custom_header
        custom_headerId
        extraAuthorizationScript
        version {
          Major
          Minor
          Build
          Revision
          MajorRevision
          MinorRevision
        }
        moduleIds
        enableBackAction
        backAction {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        description
        requiredExtraAuthorization
        allowAnonymous
        autoReload
        interval
        path
        initial_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isInvEvent
        inv_evt_second
        inv_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isDcEvent
        dc_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        use_ext_db
        ext_db_id
      }
    }
  }
`;

/**
 * Query Schemas DTO list
 */
export const QUERY_SCHEMAS_DTO = gql`
  query QuerySchemasDto(
    $filter: GeneralCollectionFilterInput,
    $custominput: Dictionary
  ) {
    response: query_Schemas_dto(filter: $filter, custominput: $custominput) {
      code
      message
      records
      data {
        _id
        panelType
        allowAI
        faIcon
        inherit_sync_schemas {
          base_schema
          inherited_props
        }
        linked_reports
        linked_documents
        linked_timeline_flows
        deleteCascade
        enable_prop_ext
        max_prop_ext
        use_update_trigger
        use_post_update_trigger
        segment_by_schema_name
        property_groups {
          name
          view_layout
          form_layout
          showLabel
          style {
            gap
            dense
            maxWidth
            alignItems
            justifyContent
            labelPosition
          }
        }
        is_system_schema
        use_saved_trigger
        use_delete_trigger
        use_authorization_trigger
        update_trigger_script
        post_update_trigger_script
        saved_trigger_script
        delete_trigger_script
        authorization_script
        disable
        is_tenant
        auto_update_if_duplicate
        auto_applychange_to_all_view
        auto_applychange_to_all_form
        prefer_view_panel_type
        formGroupType
        manualFormLayout
        defaultDetailPanelId
        defaultDetailPanelType
        not_validate_import
        not_validate_delete
        is_view
        schema_of_view
        debug
        displayOutputLog
        is_org_chart
        parentIdKey
        approval {
          enabled
          enable_approval_event
          on_approval_script
          enable_auto_mapping
          event_mappings {
            eventType
            mappings {
              propertyName
              valueExpression
            }
          }
          defaultDueAfter {
            Ticks
            Days
            Hours
            Milliseconds
            Microseconds
            Nanoseconds
            Minutes
            Seconds
            TotalDays
            TotalHours
            TotalMilliseconds
            TotalMicroseconds
            TotalNanoseconds
            TotalMinutes
            TotalSeconds
          }
        }
        conditionalGuardrails {
          name
          condition_field
          op
          condition_values
          fields
          exclude_fields
          message
          override_permission
          block_request
          apply_on_create
          when_changed_only
        }
        rls {
          rls_enabled
          rowAccessDefaults
          rowAccessRules {
            name
            applies_to {
              roles
              role_types
              positions
              departments
              current_user_department
            }
            scope
            operations {
              read
              update
              delete
            }
            extra_condition {
              field
              op
              values
            }
            message
          }
          allow_tenant_override
          tenant_override_whitelist {
            allow_override_owd
            allow_add_rules
            allow_weaken_rules
            allowed_owner_strategies
            allowed_department_strategies
            allow_client_set_owner
            allow_client_set_department
          }
          owner_strategy
          owner_payload_field
          owner_fixed_accountId
          allow_client_set_owner
          department_strategy
          department_payload_field
          department_from_field
          department_fixed_id
          allow_client_set_department
          rebuild_orgPath_on_update
          clone_keep_source_owner
          clone_keep_source_department
          access_owner_field
          access_department_field
        }
        chatboxSetting {
          enable_file_sharing
          enable_mentions
          enable_reactions
          default_visibility
          enable_comment
          enable_edit
          related_schema_policies {
            target_schema
            label
            direction
            source_prop_id
            target_prop_id
            required_permission
          }
          enable_sub_threads
          max_thread_depth
          auto_threads {
            thread_code
            thread_type
            title_template
            visibility
            singleton
            settings {
              allow_anonymous
              share_link_expiration_days
              auto_generate_share_link
              require_approval
              default_approver_role
              hide_from_external
              auto_archive_on_close
            }
          }
          allowed_thread_types
          merge_rule_setting {
            internal_view_strategy
            customer_view_strategy
            reply_target_strategy
            share_toggle_effect
          }
        }
        apis
        groupUniqueProps
        groupIndexProps {
          Capacity
          Count
          Item
        }
        controllers
        name
        keyField
        enable_log
        is_version
        is_draft
        is_private_resource
        collection
        tags
        label
        isNative
        use_extra_view_pipeline
        extra_view_pipeline
        error_message
        depended_schemas {
          targetSchema
          targetPropId
          targetPropType
          sourcePropId
          viewId
          name
        }
        delete_dependances
        update_dependances
        should_delete_dependances
        type
        no_header
        enableBc
        actions {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        maxActiveAction
        is_custom_header
        custom_headerId
        extraAuthorizationScript
        version {
          Major
          Minor
          Build
          Revision
          MajorRevision
          MinorRevision
        }
        moduleIds
        enableBackAction
        backAction {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        description
        requiredExtraAuthorization
        allowAnonymous
        autoReload
        interval
        path
        initial_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isInvEvent
        inv_evt_second
        inv_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        isDcEvent
        dc_action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        use_ext_db
        ext_db_id
      }
    }
  }
`;
