import { gql } from 'graphql-tag';

/**
 * Find SystemField DTO with typed data
 */
export const FIND_SYSTEMFIELD_DTO = gql`
  query FindSystemFieldDto($_id: String!, $custominput: Dictionary) {
    response: find_SystemField_dto(_id: $_id, custominput: $custominput) {
      code
      message
      data {
        _id
        createdAt
        updatedAt
        createdBy
        updatedBy
        code
        label
        required
        format
        view_style
        groupId
        refSchemas
        propType
        value_options {
          value
          label
          hints
          color
          faIcon
          cssClass
          style
          tooltip
          group
          order
          disabled
          hidden
          disabledWhen
          visibleWhen
        }
        nested {
          code
          label
          required
          format
          view_style
          groupId
          refSchemas
          propType
          value_options {
            value
            label
            hints
            color
            faIcon
            cssClass
            style
            tooltip
            group
            order
            disabled
            hidden
            disabledWhen
            visibleWhen
          }
          nested {
            code
            label
            required
            format
            view_style
            groupId
            refSchemas
            propType
            value_options {
              value
              label
              hints
              color
              faIcon
              cssClass
              style
              tooltip
              group
              order
              disabled
              hidden
              disabledWhen
              visibleWhen
            }
            nested {
              code
              label
              required
              format
              view_style
              groupId
              refSchemas
              propType
              value_options {
                value
                label
                hints
                color
                faIcon
                cssClass
                style
                tooltip
                group
                order
                disabled
                hidden
                disabledWhen
                visibleWhen
              }
              nested {
                code
                label
                required
                format
                view_style
                groupId
                refSchemas
                propType
                value_options
                nested
                cloneCount
                createdBy
                updatedBy
                createdAt
                updatedAt
                isDeleted
                tags
                description
                faIcon
                hints
                inSensitive
                placeholder
                action_style
                viewHeight
                action_steps
                useDefaultScript
                defaultJsScript
                defaultValue
                minValue
                maxValue
                align
                step
                editor
                aggregation
                aggregation_script
                inline_actions
                formWidth
                formHeight
                colTabWidth
                colTabFixed
                client_rules
                textEditOption
                fileUploadOption
                nestedEditOption
                runtimeOption
                referenceOption
                objectOption
                lookupsOption
                componentOption
                autoGenerateOption
                id
              }
              cloneCount
              createdBy
              updatedBy
              createdAt
              updatedAt
              isDeleted
              tags
              description
              faIcon
              hints
              inSensitive
              placeholder
              action_style
              viewHeight
              action_steps {
                subject
                type
                disabled
                setting
                is_skip_condition
                is_terminate_condition
                skip_condition
                show_confirm_message
                confirm_message
                confirm_type
                confirm_ok_label
                confirm_cancel_label
                show_finish_message
                finish_message
                finish_message_type
                terminate_condition
                show_loading
                loading_message
              }
              useDefaultScript
              defaultJsScript
              defaultValue
              minValue
              maxValue
              align
              step
              editor
              aggregation
              aggregation_script
              inline_actions {
                name
                steps
                placement
                trackClickBegin
                trackClickEnd
                enableDisplayCondition
                displayCondition
                isSubmitForm
                use_api_check_executable
                api_check_executable
                key
                className
                faIcon
                style
                data_grid
              }
              formWidth
              formHeight
              colTabWidth
              colTabFixed
              client_rules {
                event
                action
              }
              textEditOption {
                maxCharacters
                maxLength
                maxWords
                minCharacters
                minLength
                minWords
                patternMessage
                pattern
                isProgress
                suggest_method
                suggest_value
                maxCol
                maxRow
                isModifyCode
                modifyCodeTemplate
                height
                btnUploadLabel
                uploadTemplate
                disableScript
                itemHtml
              }
              fileUploadOption {
                enable_extension
                extensions
                view_as_media
                preview_mode
                folder
                max_size
              }
              nestedEditOption {
                minItem
                maxItem
                enable_create_btn
                enable_checkable
                enable_clone_btn
                enable_edit_btn
                enable_delete_btn
                enable_quick_edit
                enable_import
                is_api_extractor
                api_extractor
                enable_export
                enable_delete_all
                default_expand
                pageSize
                isPagination
                enable_search
                enable_index
                filterableIds
                searchableIds
                sectionFieldId
                itemFieldId
                sortedBys
                gridColumns
                allowReorder
                debounceMs
              }
              runtimeOption {
                resolverType
                dependencies
                script
                cacheDuration
                timeoutSeconds
              }
              referenceOption {
                minItem
                maxItem
                nativeSearch
                searchFilter
                orgSearch
                orgField
                orgResolver
                includeLinkedAccount
                cacheDuration
                showSchemaSelector
              }
              objectOption {
                view_mode
                view_visible_fields
                view_template
              }
              lookupsOption {
                target_field
                target_type
                target_schemas
                aggregation
                conditions
                logic
              }
              componentOption {
                panelId
                panelType
                inputData
              }
              autoGenerateOption {
                enabled
                parts
                separator
                allowOverride
                showPreview
                ensureUnique
                duplicateStrategy
                maxRetries
                regenerateOnEdit
                generateWhen
                sequenceScope
              }
              id
            }
            cloneCount
            createdBy
            updatedBy
            createdAt
            updatedAt
            isDeleted
            tags
            description
            faIcon
            hints
            inSensitive
            placeholder
            action_style
            viewHeight
            action_steps {
              subject
              type
              disabled
              setting
              is_skip_condition
              is_terminate_condition
              skip_condition
              show_confirm_message
              confirm_message
              confirm_type
              confirm_ok_label
              confirm_cancel_label
              show_finish_message
              finish_message
              finish_message_type
              terminate_condition
              show_loading
              loading_message
            }
            useDefaultScript
            defaultJsScript
            defaultValue
            minValue
            maxValue
            align
            step
            editor
            aggregation
            aggregation_script
            inline_actions {
              name
              steps {
                subject
                type
                disabled
                setting
                is_skip_condition
                is_terminate_condition
                skip_condition
                show_confirm_message
                confirm_message
                confirm_type
                confirm_ok_label
                confirm_cancel_label
                show_finish_message
                finish_message
                finish_message_type
                terminate_condition
                show_loading
                loading_message
              }
              placement
              trackClickBegin
              trackClickEnd
              enableDisplayCondition
              displayCondition
              isSubmitForm
              use_api_check_executable
              api_check_executable
              key
              className
              faIcon
              style
              data_grid {
                x
                y
                w
                h
                static
                minW
                minH
                isResizable
                isDraggable
                isBounded
              }
            }
            formWidth
            formHeight
            colTabWidth
            colTabFixed
            client_rules {
              event
              action
            }
            textEditOption {
              maxCharacters
              maxLength
              maxWords
              minCharacters
              minLength
              minWords
              patternMessage
              pattern
              isProgress
              suggest_method
              suggest_value
              maxCol
              maxRow
              isModifyCode
              modifyCodeTemplate
              height
              btnUploadLabel
              uploadTemplate
              disableScript
              itemHtml
            }
            fileUploadOption {
              enable_extension
              extensions
              view_as_media
              preview_mode
              folder
              max_size
            }
            nestedEditOption {
              minItem
              maxItem
              enable_create_btn
              enable_checkable
              enable_clone_btn
              enable_edit_btn
              enable_delete_btn
              enable_quick_edit
              enable_import
              is_api_extractor
              api_extractor
              enable_export
              enable_delete_all
              default_expand
              pageSize
              isPagination
              enable_search
              enable_index
              filterableIds
              searchableIds
              sectionFieldId
              itemFieldId
              sortedBys
              gridColumns
              allowReorder
              debounceMs
            }
            runtimeOption {
              resolverType
              dependencies {
                Chars
                Length
              }
              script
              cacheDuration
              timeoutSeconds
            }
            referenceOption {
              minItem
              maxItem
              nativeSearch
              searchFilter {
                op
                refcollection
                refalias
                children
                id
                value
                propType
                namespace
                operation
                customQuery
                rawFilter
              }
              orgSearch
              orgField
              orgResolver
              includeLinkedAccount
              cacheDuration
              showSchemaSelector
            }
            objectOption {
              view_mode
              view_visible_fields
              view_template
            }
            lookupsOption {
              target_field
              target_type
              target_schemas {
                Length
                LongLength
                Rank
                SyncRoot
                IsReadOnly
                IsFixedSize
                IsSynchronized
              }
              aggregation
              conditions {
                source
                target
                operator
                isexact
                values
                type
              }
              logic
            }
            componentOption {
              panelId
              panelType
              inputData
            }
            autoGenerateOption {
              enabled
              parts {
                type
                value
                length
                resetCycle
                startFrom
                step
                source
                format
                timezone
                fieldName
                transforms
                fallback
                randomType
                randomLength
                script
              }
              separator
              allowOverride
              showPreview
              ensureUnique
              duplicateStrategy
              maxRetries
              regenerateOnEdit
              generateWhen
              sequenceScope
            }
            id
          }
          cloneCount
          createdBy
          updatedBy
          createdAt
          updatedAt
          isDeleted
          tags
          description
          faIcon
          hints
          inSensitive
          placeholder
          action_style
          viewHeight
          action_steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          useDefaultScript
          defaultJsScript
          defaultValue
          minValue
          maxValue
          align
          step
          editor
          aggregation
          aggregation_script
          inline_actions {
            name
            steps {
              subject
              type
              disabled
              setting
              is_skip_condition
              is_terminate_condition
              skip_condition
              show_confirm_message
              confirm_message
              confirm_type
              confirm_ok_label
              confirm_cancel_label
              show_finish_message
              finish_message
              finish_message_type
              terminate_condition
              show_loading
              loading_message
            }
            placement
            trackClickBegin
            trackClickEnd
            enableDisplayCondition
            displayCondition
            isSubmitForm
            use_api_check_executable
            api_check_executable
            key
            className
            faIcon
            style
            data_grid {
              x
              y
              w
              h
              static
              minW
              minH
              isResizable
              isDraggable
              isBounded
            }
          }
          formWidth
          formHeight
          colTabWidth
          colTabFixed
          client_rules {
            event
            action
          }
          textEditOption {
            maxCharacters
            maxLength
            maxWords
            minCharacters
            minLength
            minWords
            patternMessage
            pattern
            isProgress
            suggest_method
            suggest_value
            maxCol
            maxRow
            isModifyCode
            modifyCodeTemplate
            height
            btnUploadLabel
            uploadTemplate
            disableScript
            itemHtml
          }
          fileUploadOption {
            enable_extension
            extensions
            view_as_media
            preview_mode
            folder
            max_size
          }
          nestedEditOption {
            minItem
            maxItem
            enable_create_btn
            enable_checkable
            enable_clone_btn
            enable_edit_btn
            enable_delete_btn
            enable_quick_edit
            enable_import
            is_api_extractor
            api_extractor
            enable_export
            enable_delete_all
            default_expand
            pageSize
            isPagination
            enable_search
            enable_index
            filterableIds
            searchableIds
            sectionFieldId
            itemFieldId
            sortedBys
            gridColumns
            allowReorder
            debounceMs
          }
          runtimeOption {
            resolverType
            dependencies {
              Chars
              Length
            }
            script
            cacheDuration
            timeoutSeconds
          }
          referenceOption {
            minItem
            maxItem
            nativeSearch
            searchFilter {
              op
              refcollection
              refalias
              children {
                op
                refcollection
                refalias
                children
                id
                value
                propType
                namespace
                operation
                customQuery
                rawFilter
              }
              id
              value
              propType
              namespace
              operation
              customQuery
              rawFilter
            }
            orgSearch
            orgField
            orgResolver
            includeLinkedAccount
            cacheDuration
            showSchemaSelector
          }
          objectOption {
            view_mode
            view_visible_fields
            view_template
          }
          lookupsOption {
            target_field
            target_type
            target_schemas {
              Length
              LongLength
              Rank
              SyncRoot
              IsReadOnly
              IsFixedSize
              IsSynchronized
            }
            aggregation
            conditions {
              source
              target
              operator
              isexact
              values
              type
            }
            logic
          }
          componentOption {
            panelId
            panelType
            inputData
          }
          autoGenerateOption {
            enabled
            parts {
              type
              value
              length
              resetCycle
              startFrom
              step
              source
              format
              timezone
              fieldName
              transforms
              fallback
              randomType
              randomLength
              script
            }
            separator
            allowOverride
            showPreview
            ensureUnique
            duplicateStrategy
            maxRetries
            regenerateOnEdit
            generateWhen
            sequenceScope
          }
          id
        }
        cloneCount
        isDeleted
        tags
        description
        faIcon
        hints
        inSensitive
        placeholder
        action_style
        viewHeight
        action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        useDefaultScript
        defaultJsScript
        defaultValue
        minValue
        maxValue
        align
        step
        editor
        aggregation
        aggregation_script
        inline_actions {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        formWidth
        formHeight
        colTabWidth
        colTabFixed
        client_rules {
          event
          action
        }
        textEditOption {
          maxCharacters
          maxLength
          maxWords
          minCharacters
          minLength
          minWords
          patternMessage
          pattern
          isProgress
          suggest_method
          suggest_value
          maxCol
          maxRow
          isModifyCode
          modifyCodeTemplate
          height
          btnUploadLabel
          uploadTemplate
          disableScript
          itemHtml
        }
        fileUploadOption {
          enable_extension
          extensions
          view_as_media
          preview_mode
          folder
          max_size
        }
        nestedEditOption {
          minItem
          maxItem
          enable_create_btn
          enable_checkable
          enable_clone_btn
          enable_edit_btn
          enable_delete_btn
          enable_quick_edit
          enable_import
          is_api_extractor
          api_extractor
          enable_export
          enable_delete_all
          default_expand
          pageSize
          isPagination
          enable_search
          enable_index
          filterableIds
          searchableIds
          sectionFieldId
          itemFieldId
          sortedBys
          gridColumns
          allowReorder
          debounceMs
        }
        runtimeOption {
          resolverType
          dependencies {
            Chars
            Length
          }
          script
          cacheDuration
          timeoutSeconds
        }
        referenceOption {
          minItem
          maxItem
          nativeSearch
          searchFilter {
            op
            refcollection
            refalias
            children {
              op
              refcollection
              refalias
              children {
                op
                refcollection
                refalias
                children
                id
                value
                propType
                namespace
                operation
                customQuery
                rawFilter
              }
              id
              value
              propType
              namespace
              operation
              customQuery
              rawFilter
            }
            id
            value
            propType
            namespace
            operation
            customQuery
            rawFilter
          }
          orgSearch
          orgField
          orgResolver
          includeLinkedAccount
          cacheDuration
          showSchemaSelector
        }
        objectOption {
          view_mode
          view_visible_fields
          view_template
        }
        lookupsOption {
          target_field
          target_type
          target_schemas {
            Length
            LongLength
            Rank
            SyncRoot
            IsReadOnly
            IsFixedSize
            IsSynchronized
          }
          aggregation
          conditions {
            source
            target
            operator
            isexact
            values
            type
          }
          logic
        }
        componentOption {
          panelId
          panelType
          inputData
        }
        autoGenerateOption {
          enabled
          parts {
            type
            value
            length
            resetCycle
            startFrom
            step
            source
            format
            timezone
            fieldName
            transforms
            fallback
            randomType
            randomLength
            script
          }
          separator
          allowOverride
          showPreview
          ensureUnique
          duplicateStrategy
          maxRetries
          regenerateOnEdit
          generateWhen
          sequenceScope
        }
        viewSetting {
          defaultHidden
          colTabWidth
          aggregation
          aggregation_script
          is_html
          displayHtml
          format
          formula
          item_no_label
          display_style
          enableViewTooltip
          tooltipHtml
          view_style
          viewHeight
          colTabFixed
          align
          view_lbl_by_suggest
          is_advance_table_filter
        }
      }
    }
  }
`;

/**
 * Query SystemFields DTO list
 */
export const QUERY_SYSTEMFIELDS_DTO = gql`
  query QuerySystemFieldsDto(
    $filter: GeneralCollectionFilterInput,
    $custominput: Dictionary
  ) {
    response: query_SystemFields_dto(filter: $filter, custominput: $custominput) {
      code
      message
      records
      data {
        _id
        code
        label
        required
        format
        view_style
        groupId
        refSchemas
        propType
        value_options {
          value
          label
          hints
          color
          faIcon
          cssClass
          style
          tooltip
          group
          order
          disabled
          hidden
          disabledWhen
          visibleWhen
        }
        nested {
          code
          label
          required
          format
          view_style
          groupId
          refSchemas
          propType
          value_options {
            value
            label
            hints
            color
            faIcon
            cssClass
            style
            tooltip
            group
            order
            disabled
            hidden
            disabledWhen
            visibleWhen
          }
          nested {
            code
            label
            required
            format
            view_style
            groupId
            refSchemas
            propType
            value_options {
              value
              label
              hints
              color
              faIcon
              cssClass
              style
              tooltip
              group
              order
              disabled
              hidden
              disabledWhen
              visibleWhen
            }
            nested {
              code
              label
              required
              format
              view_style
              groupId
              refSchemas
              propType
              value_options {
                value
                label
                hints
                color
                faIcon
                cssClass
                style
                tooltip
                group
                order
                disabled
                hidden
                disabledWhen
                visibleWhen
              }
              nested {
                code
                label
                required
                format
                view_style
                groupId
                refSchemas
                propType
                value_options
                nested
                cloneCount
                createdBy
                updatedBy
                createdAt
                updatedAt
                isDeleted
                tags
                description
                faIcon
                hints
                inSensitive
                placeholder
                action_style
                viewHeight
                action_steps
                useDefaultScript
                defaultJsScript
                defaultValue
                minValue
                maxValue
                align
                step
                editor
                aggregation
                aggregation_script
                inline_actions
                formWidth
                formHeight
                colTabWidth
                colTabFixed
                client_rules
                textEditOption
                fileUploadOption
                nestedEditOption
                runtimeOption
                referenceOption
                objectOption
                lookupsOption
                componentOption
                autoGenerateOption
                id
              }
              cloneCount
              createdBy
              updatedBy
              createdAt
              updatedAt
              isDeleted
              tags
              description
              faIcon
              hints
              inSensitive
              placeholder
              action_style
              viewHeight
              action_steps {
                subject
                type
                disabled
                setting
                is_skip_condition
                is_terminate_condition
                skip_condition
                show_confirm_message
                confirm_message
                confirm_type
                confirm_ok_label
                confirm_cancel_label
                show_finish_message
                finish_message
                finish_message_type
                terminate_condition
                show_loading
                loading_message
              }
              useDefaultScript
              defaultJsScript
              defaultValue
              minValue
              maxValue
              align
              step
              editor
              aggregation
              aggregation_script
              inline_actions {
                name
                steps
                placement
                trackClickBegin
                trackClickEnd
                enableDisplayCondition
                displayCondition
                isSubmitForm
                use_api_check_executable
                api_check_executable
                key
                className
                faIcon
                style
                data_grid
              }
              formWidth
              formHeight
              colTabWidth
              colTabFixed
              client_rules {
                event
                action
              }
              textEditOption {
                maxCharacters
                maxLength
                maxWords
                minCharacters
                minLength
                minWords
                patternMessage
                pattern
                isProgress
                suggest_method
                suggest_value
                maxCol
                maxRow
                isModifyCode
                modifyCodeTemplate
                height
                btnUploadLabel
                uploadTemplate
                disableScript
                itemHtml
              }
              fileUploadOption {
                enable_extension
                extensions
                view_as_media
                preview_mode
                folder
                max_size
              }
              nestedEditOption {
                minItem
                maxItem
                enable_create_btn
                enable_checkable
                enable_clone_btn
                enable_edit_btn
                enable_delete_btn
                enable_quick_edit
                enable_import
                is_api_extractor
                api_extractor
                enable_export
                enable_delete_all
                default_expand
                pageSize
                isPagination
                enable_search
                enable_index
                filterableIds
                searchableIds
                sectionFieldId
                itemFieldId
                sortedBys
                gridColumns
                allowReorder
                debounceMs
              }
              runtimeOption {
                resolverType
                dependencies
                script
                cacheDuration
                timeoutSeconds
              }
              referenceOption {
                minItem
                maxItem
                nativeSearch
                searchFilter
                orgSearch
                orgField
                orgResolver
                includeLinkedAccount
                cacheDuration
                showSchemaSelector
              }
              objectOption {
                view_mode
                view_visible_fields
                view_template
              }
              lookupsOption {
                target_field
                target_type
                target_schemas
                aggregation
                conditions
                logic
              }
              componentOption {
                panelId
                panelType
                inputData
              }
              autoGenerateOption {
                enabled
                parts
                separator
                allowOverride
                showPreview
                ensureUnique
                duplicateStrategy
                maxRetries
                regenerateOnEdit
                generateWhen
                sequenceScope
              }
              id
            }
            cloneCount
            createdBy
            updatedBy
            createdAt
            updatedAt
            isDeleted
            tags
            description
            faIcon
            hints
            inSensitive
            placeholder
            action_style
            viewHeight
            action_steps {
              subject
              type
              disabled
              setting
              is_skip_condition
              is_terminate_condition
              skip_condition
              show_confirm_message
              confirm_message
              confirm_type
              confirm_ok_label
              confirm_cancel_label
              show_finish_message
              finish_message
              finish_message_type
              terminate_condition
              show_loading
              loading_message
            }
            useDefaultScript
            defaultJsScript
            defaultValue
            minValue
            maxValue
            align
            step
            editor
            aggregation
            aggregation_script
            inline_actions {
              name
              steps {
                subject
                type
                disabled
                setting
                is_skip_condition
                is_terminate_condition
                skip_condition
                show_confirm_message
                confirm_message
                confirm_type
                confirm_ok_label
                confirm_cancel_label
                show_finish_message
                finish_message
                finish_message_type
                terminate_condition
                show_loading
                loading_message
              }
              placement
              trackClickBegin
              trackClickEnd
              enableDisplayCondition
              displayCondition
              isSubmitForm
              use_api_check_executable
              api_check_executable
              key
              className
              faIcon
              style
              data_grid {
                x
                y
                w
                h
                static
                minW
                minH
                isResizable
                isDraggable
                isBounded
              }
            }
            formWidth
            formHeight
            colTabWidth
            colTabFixed
            client_rules {
              event
              action
            }
            textEditOption {
              maxCharacters
              maxLength
              maxWords
              minCharacters
              minLength
              minWords
              patternMessage
              pattern
              isProgress
              suggest_method
              suggest_value
              maxCol
              maxRow
              isModifyCode
              modifyCodeTemplate
              height
              btnUploadLabel
              uploadTemplate
              disableScript
              itemHtml
            }
            fileUploadOption {
              enable_extension
              extensions
              view_as_media
              preview_mode
              folder
              max_size
            }
            nestedEditOption {
              minItem
              maxItem
              enable_create_btn
              enable_checkable
              enable_clone_btn
              enable_edit_btn
              enable_delete_btn
              enable_quick_edit
              enable_import
              is_api_extractor
              api_extractor
              enable_export
              enable_delete_all
              default_expand
              pageSize
              isPagination
              enable_search
              enable_index
              filterableIds
              searchableIds
              sectionFieldId
              itemFieldId
              sortedBys
              gridColumns
              allowReorder
              debounceMs
            }
            runtimeOption {
              resolverType
              dependencies {
                Chars
                Length
              }
              script
              cacheDuration
              timeoutSeconds
            }
            referenceOption {
              minItem
              maxItem
              nativeSearch
              searchFilter {
                op
                refcollection
                refalias
                children
                id
                value
                propType
                namespace
                operation
                customQuery
                rawFilter
              }
              orgSearch
              orgField
              orgResolver
              includeLinkedAccount
              cacheDuration
              showSchemaSelector
            }
            objectOption {
              view_mode
              view_visible_fields
              view_template
            }
            lookupsOption {
              target_field
              target_type
              target_schemas {
                Length
                LongLength
                Rank
                SyncRoot
                IsReadOnly
                IsFixedSize
                IsSynchronized
              }
              aggregation
              conditions {
                source
                target
                operator
                isexact
                values
                type
              }
              logic
            }
            componentOption {
              panelId
              panelType
              inputData
            }
            autoGenerateOption {
              enabled
              parts {
                type
                value
                length
                resetCycle
                startFrom
                step
                source
                format
                timezone
                fieldName
                transforms
                fallback
                randomType
                randomLength
                script
              }
              separator
              allowOverride
              showPreview
              ensureUnique
              duplicateStrategy
              maxRetries
              regenerateOnEdit
              generateWhen
              sequenceScope
            }
            id
          }
          cloneCount
          createdBy
          updatedBy
          createdAt
          updatedAt
          isDeleted
          tags
          description
          faIcon
          hints
          inSensitive
          placeholder
          action_style
          viewHeight
          action_steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          useDefaultScript
          defaultJsScript
          defaultValue
          minValue
          maxValue
          align
          step
          editor
          aggregation
          aggregation_script
          inline_actions {
            name
            steps {
              subject
              type
              disabled
              setting
              is_skip_condition
              is_terminate_condition
              skip_condition
              show_confirm_message
              confirm_message
              confirm_type
              confirm_ok_label
              confirm_cancel_label
              show_finish_message
              finish_message
              finish_message_type
              terminate_condition
              show_loading
              loading_message
            }
            placement
            trackClickBegin
            trackClickEnd
            enableDisplayCondition
            displayCondition
            isSubmitForm
            use_api_check_executable
            api_check_executable
            key
            className
            faIcon
            style
            data_grid {
              x
              y
              w
              h
              static
              minW
              minH
              isResizable
              isDraggable
              isBounded
            }
          }
          formWidth
          formHeight
          colTabWidth
          colTabFixed
          client_rules {
            event
            action
          }
          textEditOption {
            maxCharacters
            maxLength
            maxWords
            minCharacters
            minLength
            minWords
            patternMessage
            pattern
            isProgress
            suggest_method
            suggest_value
            maxCol
            maxRow
            isModifyCode
            modifyCodeTemplate
            height
            btnUploadLabel
            uploadTemplate
            disableScript
            itemHtml
          }
          fileUploadOption {
            enable_extension
            extensions
            view_as_media
            preview_mode
            folder
            max_size
          }
          nestedEditOption {
            minItem
            maxItem
            enable_create_btn
            enable_checkable
            enable_clone_btn
            enable_edit_btn
            enable_delete_btn
            enable_quick_edit
            enable_import
            is_api_extractor
            api_extractor
            enable_export
            enable_delete_all
            default_expand
            pageSize
            isPagination
            enable_search
            enable_index
            filterableIds
            searchableIds
            sectionFieldId
            itemFieldId
            sortedBys
            gridColumns
            allowReorder
            debounceMs
          }
          runtimeOption {
            resolverType
            dependencies {
              Chars
              Length
            }
            script
            cacheDuration
            timeoutSeconds
          }
          referenceOption {
            minItem
            maxItem
            nativeSearch
            searchFilter {
              op
              refcollection
              refalias
              children {
                op
                refcollection
                refalias
                children
                id
                value
                propType
                namespace
                operation
                customQuery
                rawFilter
              }
              id
              value
              propType
              namespace
              operation
              customQuery
              rawFilter
            }
            orgSearch
            orgField
            orgResolver
            includeLinkedAccount
            cacheDuration
            showSchemaSelector
          }
          objectOption {
            view_mode
            view_visible_fields
            view_template
          }
          lookupsOption {
            target_field
            target_type
            target_schemas {
              Length
              LongLength
              Rank
              SyncRoot
              IsReadOnly
              IsFixedSize
              IsSynchronized
            }
            aggregation
            conditions {
              source
              target
              operator
              isexact
              values
              type
            }
            logic
          }
          componentOption {
            panelId
            panelType
            inputData
          }
          autoGenerateOption {
            enabled
            parts {
              type
              value
              length
              resetCycle
              startFrom
              step
              source
              format
              timezone
              fieldName
              transforms
              fallback
              randomType
              randomLength
              script
            }
            separator
            allowOverride
            showPreview
            ensureUnique
            duplicateStrategy
            maxRetries
            regenerateOnEdit
            generateWhen
            sequenceScope
          }
          id
        }
        cloneCount
        isDeleted
        tags
        description
        faIcon
        hints
        inSensitive
        placeholder
        action_style
        viewHeight
        action_steps {
          subject
          type
          disabled
          setting
          is_skip_condition
          is_terminate_condition
          skip_condition
          show_confirm_message
          confirm_message
          confirm_type
          confirm_ok_label
          confirm_cancel_label
          show_finish_message
          finish_message
          finish_message_type
          terminate_condition
          show_loading
          loading_message
        }
        useDefaultScript
        defaultJsScript
        defaultValue
        minValue
        maxValue
        align
        step
        editor
        aggregation
        aggregation_script
        inline_actions {
          name
          steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          placement
          trackClickBegin
          trackClickEnd
          enableDisplayCondition
          displayCondition
          isSubmitForm
          use_api_check_executable
          api_check_executable
          key
          className
          faIcon
          style
          data_grid {
            x
            y
            w
            h
            static
            minW
            minH
            isResizable
            isDraggable
            isBounded
          }
        }
        formWidth
        formHeight
        colTabWidth
        colTabFixed
        client_rules {
          event
          action
        }
        textEditOption {
          maxCharacters
          maxLength
          maxWords
          minCharacters
          minLength
          minWords
          patternMessage
          pattern
          isProgress
          suggest_method
          suggest_value
          maxCol
          maxRow
          isModifyCode
          modifyCodeTemplate
          height
          btnUploadLabel
          uploadTemplate
          disableScript
          itemHtml
        }
        fileUploadOption {
          enable_extension
          extensions
          view_as_media
          preview_mode
          folder
          max_size
        }
        nestedEditOption {
          minItem
          maxItem
          enable_create_btn
          enable_checkable
          enable_clone_btn
          enable_edit_btn
          enable_delete_btn
          enable_quick_edit
          enable_import
          is_api_extractor
          api_extractor
          enable_export
          enable_delete_all
          default_expand
          pageSize
          isPagination
          enable_search
          enable_index
          filterableIds
          searchableIds
          sectionFieldId
          itemFieldId
          sortedBys
          gridColumns
          allowReorder
          debounceMs
        }
        runtimeOption {
          resolverType
          dependencies {
            Chars
            Length
          }
          script
          cacheDuration
          timeoutSeconds
        }
        referenceOption {
          minItem
          maxItem
          nativeSearch
          searchFilter {
            op
            refcollection
            refalias
            children {
              op
              refcollection
              refalias
              children {
                op
                refcollection
                refalias
                children
                id
                value
                propType
                namespace
                operation
                customQuery
                rawFilter
              }
              id
              value
              propType
              namespace
              operation
              customQuery
              rawFilter
            }
            id
            value
            propType
            namespace
            operation
            customQuery
            rawFilter
          }
          orgSearch
          orgField
          orgResolver
          includeLinkedAccount
          cacheDuration
          showSchemaSelector
        }
        objectOption {
          view_mode
          view_visible_fields
          view_template
        }
        lookupsOption {
          target_field
          target_type
          target_schemas {
            Length
            LongLength
            Rank
            SyncRoot
            IsReadOnly
            IsFixedSize
            IsSynchronized
          }
          aggregation
          conditions {
            source
            target
            operator
            isexact
            values
            type
          }
          logic
        }
        componentOption {
          panelId
          panelType
          inputData
        }
        autoGenerateOption {
          enabled
          parts {
            type
            value
            length
            resetCycle
            startFrom
            step
            source
            format
            timezone
            fieldName
            transforms
            fallback
            randomType
            randomLength
            script
          }
          separator
          allowOverride
          showPreview
          ensureUnique
          duplicateStrategy
          maxRetries
          regenerateOnEdit
          generateWhen
          sequenceScope
        }
        viewSetting {
          defaultHidden
          colTabWidth
          aggregation
          aggregation_script
          is_html
          displayHtml
          format
          formula
          item_no_label
          display_style
          enableViewTooltip
          tooltipHtml
          view_style
          viewHeight
          colTabFixed
          align
          view_lbl_by_suggest
          is_advance_table_filter
        }
      }
    }
  }
`;
