import { gql } from 'graphql-tag';

/**
 * Find TenantRegistration DTO with typed data
 */
export const FIND_TENANTREGISTRATION_DTO = gql`
  query FindTenantRegistrationDto($_id: String!, $custominput: Dictionary) {
    response: find_TenantRegistration_dto(_id: $_id, custominput: $custominput) {
      code
      message
      data {
        _id
        createdAt
        updatedAt
        createdBy
        updatedBy
        schema
        deploymentId
        idx_deploymentId
        deploymentId
        access_link
        nonExpired
        expiredAt
        active
        realtimeState
        realtimeError
        realtimeUpdateAt
        sandbox
        issuer
        tokenExpiredAt {
          Date
          Day
          DayOfWeek
          DayOfYear
          Hour
          Kind
          Millisecond
          Microsecond
          Nanosecond
          Minute
          Month
          Second
          Ticks
          TimeOfDay {
            Ticks
            Days
            Hours
            Milliseconds
            Microseconds
            Nanoseconds
            Minutes
            Seconds
            TotalDays
            TotalHours
            TotalMilliseconds
            TotalMicroseconds
            TotalNanoseconds
            TotalMinutes
            TotalSeconds
          }
          Year
        }
        description
        code
        menus {
          name
          target_schema
          moduleIds
          panel_type
          url_type
          layoutId
          viewExtensionId
          requiredPermissions
          isDefault
          isHidden
          parentId
          type
          icon
          path
          absolutePath
          description
          level
          priority
          action_steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          isRootScope
          showBadge
          badgeScript
          badgeType
          badgeColor
          id
        }
        appstoreId
        idx_appstoreId
        appstoreId
        appVersionId
        idx_appVersionId
        appVersionId
        appDBId
        idx_appDBId
        appDBId
        dbHost
        dbPort
        dbUserName
        dbPassword
        dbName
        token
        tier
        notificationTriggerMaxRecipientsPerAction
        tenantId
      }
    }
  }
`;

/**
 * Query TenantRegistrations DTO list
 */
export const QUERY_TENANTREGISTRATIONS_DTO = gql`
  query QueryTenantRegistrationsDto(
    $filter: GeneralCollectionFilterInput,
    $custominput: Dictionary
  ) {
    response: query_TenantRegistrations_dto(filter: $filter, custominput: $custominput) {
      code
      message
      records
      data {
        _id
        schema
        deploymentId
        idx_deploymentId
        deploymentId
        access_link
        nonExpired
        expiredAt
        active
        realtimeState
        realtimeError
        realtimeUpdateAt
        sandbox
        issuer
        tokenExpiredAt {
          Date
          Day
          DayOfWeek
          DayOfYear
          Hour
          Kind
          Millisecond
          Microsecond
          Nanosecond
          Minute
          Month
          Second
          Ticks
          TimeOfDay {
            Ticks
            Days
            Hours
            Milliseconds
            Microseconds
            Nanoseconds
            Minutes
            Seconds
            TotalDays
            TotalHours
            TotalMilliseconds
            TotalMicroseconds
            TotalNanoseconds
            TotalMinutes
            TotalSeconds
          }
          Year
        }
        description
        code
        menus {
          name
          target_schema
          moduleIds
          panel_type
          url_type
          layoutId
          viewExtensionId
          requiredPermissions
          isDefault
          isHidden
          parentId
          type
          icon
          path
          absolutePath
          description
          level
          priority
          action_steps {
            subject
            type
            disabled
            setting
            is_skip_condition
            is_terminate_condition
            skip_condition
            show_confirm_message
            confirm_message
            confirm_type
            confirm_ok_label
            confirm_cancel_label
            show_finish_message
            finish_message
            finish_message_type
            terminate_condition
            show_loading
            loading_message
          }
          isRootScope
          showBadge
          badgeScript
          badgeType
          badgeColor
          id
        }
        appstoreId
        idx_appstoreId
        appstoreId
        appVersionId
        idx_appVersionId
        appVersionId
        appDBId
        idx_appDBId
        appDBId
        dbHost
        dbPort
        dbUserName
        dbPassword
        dbName
        token
        tier
        notificationTriggerMaxRecipientsPerAction
        tenantId
      }
    }
  }
`;
