export const ActionTypes = {
  // Data Actions
  NEW_DATA: 'NEWDATA',
  SET_DATA: 'SETDATA',
  VALIDATE_DATA: 'VALIDATEDATA',
  UPDATE: 'UPDATE',
  UPDATE_SET: 'UPDATE_SET',
  UPDATE_UNCONTROL: 'UPDATEUNCONTROL',
  UPDATE_SET_UNCONTROL: 'UPDATE_SET_UNCONTROL',
  DELETE: 'DELETE',
  CLONE: 'CLONE',
  
  // API Actions
  CALL_API: 'CALLAPI',
  CALLFUNCTION: 'CALLFUNCTION',
  CALLPLUGIN: 'CALLPLUGIN',
  // Dialog Actions
  POPUP: 'POPUP',
  CLOSE: 'CLOSE',
  CLOSE_ALL: 'CLOSEALL',
  SHOW_CONFIRM: 'SHOWCONFIRM',
  
  // Navigation Actions
  REDIRECT: 'REDIRECT',
  SET_QUERY_PARAMETERS: 'SETQUERYPARAMETERS',
  DETAIL: 'DETAIL',
  
  // Content Actions
  LOCK: 'LOCK',
  UNLOCK: 'UNLOCK',
  COMMIT: 'COMMIT',
  APPROVE: 'CONFIRM',
  REJECT: 'REJECT',
  
  // Import/Export Actions
  IMPORT: 'IMPORT',
  EXPORT: 'EXPORT',
  
  // UI Actions
  SHOW_MESSAGE: 'SHOWMESSAGE',
  SHOW_PREVIEW: 'SHOWPREVIEWDATA',
  SHOW_CHATBOX: 'SHOWCHATBOX',
  SHOW_VERSIONS: 'SHOWVERSIONS',
  SHOW_DETAIL_POPUP: 'SHOWDETAILPOPUP',
  SHOW_EDIT_POPUP: 'SHOWEDITPOPUP',
  COPY_TO_CLIPBOARD: 'COPYTOCLIPBOARD',
  PUSHNOTIFICATION: 'PUSHNOTIFICATION',
  // Media Actions
  TTS: 'TTS',
  TRANSLATE: 'TRANSLATE',
  PLAY_SOUND: 'PLAYSOUND',
  PRINT: 'PRINT',
  PREVIEW_HTML: 'PREVIEWHTML',
  PREVIEW_IFRAME: 'PREVIEWIFRAME',
  
  // Layout Actions
  RELOAD_LAYOUT: 'RELOADLAYOUT',
  RELOAD_PANEL: 'RELOADPANEL',
  LOAD: 'LOAD',
  SET_PANEL_DATA: 'SET_PANEL_DATA',
  
  // System Actions
  WAIT: 'WAIT',
  EXECUTE_SCRIPT: 'EXECUTESCRIPT',
  CHECK_PERMISSION: 'CHECKPERMISSION',
  LAYOUT_SUBMIT: 'LAYOUTSUBMIT',
  FINISHED: 'FINISHED'
} as const;

export type ActionType = typeof ActionTypes[keyof typeof ActionTypes]; 