/**
 * Vietnamese Labels - Tất cả labels sử dụng tiếng Việt có dấu
 */

export const LABELS = {
    // Common
    DASHBOARD: 'Tổng Quan',
    PROJECTS: 'Dự Án',
    USERS: 'Người Dùng',
    SETTINGS: 'Cài Đặt',
    LOGOUT: 'Đăng Xuất',
    PROFILE: 'Hồ Sơ',
    NOTIFICATIONS: 'Thông Báo',
    SEARCH: 'Tìm Kiếm',

    // Admin Menu
    ADMIN: {
        DASHBOARD: 'Tổng Quan',
        USER_MANAGEMENT: 'Quản Lý Người Dùng',
        ROLE_MANAGEMENT: 'Quản Lý Vai Trò',
        DEPARTMENT_HIERARCHY: 'Cấu Trúc Tổ Chức',
        SCHEMA_MANAGEMENT: 'Quản Lý Lược Đồ',
        WORKFLOW_DESIGNER: 'Thiết Kế Workflow',
        FORM_BUILDER: 'Trình Tạo Form',
        MENU_MANAGEMENT: 'Quản Lý Menu',
        SYSTEM_SETTINGS: 'Cài Đặt Hệ Thống',
        INTEGRATION_MANAGEMENT: 'Quản Lý Tích Hợp',
        EMAIL_TEMPLATES: 'Mẫu Email',
        NOTIFICATION_RULES: 'Quy Tắc Thông Báo',
        AUDIT_LOG: 'Nhật Ký Kiểm Toán',
        SECURITY_SETTINGS: 'Cài Đặt Bảo Mật',
        ACCESS_CONTROL: 'Kiểm Soát Truy Cập',
        DATA_IMPORT_EXPORT: 'Nhập/Xuất Dữ Liệu',
        BACKUP_RESTORE: 'Sao Lưu & Phục Hồi',
        PERFORMANCE_DASHBOARD: 'Dashboard Hiệu Suất',
        API_KEYS: 'Khóa API',
        ERROR_LOGS: 'Nhật Ký Lỗi',
        SYSTEM_HEALTH: 'Sức Khỏe Hệ Thống',
    },

    // Supervisor Menu
    SUPERVISOR: {
        DASHBOARD: 'Tổng Quan',
        PROJECTS: 'Dự Án',
        EVIDENCE_QUEUE: 'Hàng Đợi Minh Chứng',
        QUALITY_ISSUES: 'Vấn Đề Chất Lượng',
        TEAM_PERFORMANCE: 'Hiệu Suất Đội',
        STAFF_ATTENDANCE: 'Chấm Công Nhân Viên',
        REPORTS: 'Báo Cáo',
        ANALYTICS: 'Phân Tích',
        MATERIAL_APPROVALS: 'Phê Duyệt Vật Liệu',
        FIELD_INSPECTION: 'Kiểm Tra Công Trường',
    },

    // PM Menu
    PM: {
        DASHBOARD: 'Tổng Quan',
        PROJECTS: 'Dự Án',
        ALL_PROJECTS: 'Tất Cả Dự Án',
        MY_PROJECTS: 'Dự Án Của Tôi',
        CREATE_PROJECT: 'Tạo Dự Án',
        CONTRACTS: 'Hợp Đồng',
        ALL_CONTRACTS: 'Tất Cả Hợp Đồng',
        CREATE_CONTRACT: 'Tạo Hợp Đồng',
        TEAMS: 'Đội Nhóm',
        INTERNAL_TEAMS: 'Đội Nội Bộ',
        COLLABORATORS: 'Cộng Tác Viên',
        COLLABORATOR_DETAIL: 'Chi Tiết Cộng Tác Viên',
        CUSTOMERS: 'Khách Hàng',
        ALL_CUSTOMERS: 'Tất Cả Khách Hàng',
        ADD_CUSTOMER: 'Thêm Khách Hàng',
        FINANCIALS: 'Tài Chính',
        PAYMENT_MILESTONES: 'Mốc Thanh Toán',
        TRANSACTIONS: 'Giao Dịch',
        REPORTS: 'Báo Cáo',
        PROJECT_REPORTS: 'Báo Cáo Dự Án',
        FINANCIAL_REPORTS: 'Báo Cáo Tài Chính',
        EXPORT_DATA: 'Xuất Dữ Liệu',
        EVIDENCE_GALLERY: 'Thư Viện Minh Chứng',
        CUSTOMER_PORTAL: 'Cổng Khách Hàng',
    },

    // Accountant Menu
    ACCOUNTANT: {
        DASHBOARD: 'Tổng Quan',
        FINANCIAL_SUMMARY: 'Tổng Quan Tài Chính',
        PROJECT_FINANCIAL: 'Tài Chính Dự Án',
        PAYMENT_TRACKING: 'Theo Dõi Thanh Toán',
        TRANSACTIONS: 'Giao Dịch',
        INVOICES: 'Hóa Đơn',
        REPORTS: 'Báo Cáo',
        REVENUE_REPORT: 'Báo Cáo Doanh Thu',
        EXPENSE_REPORT: 'Báo Cáo Chi Phí',
        PROFIT_LOSS: 'Lãi/Lỗ',
    },

    // Partner (Outsource Leader) Menu
    PARTNER: {
        DASHBOARD: 'Tổng Quan',
        MY_PROJECTS: 'Dự Án Của Tôi',
        UPLOAD_EVIDENCE: 'Tải Minh Chứng',
        MATERIALS: 'Vật Liệu',
        LABOR: 'Nhân Công',
        PAYMENTS: 'Thanh Toán',
        QUALITY_ISSUES: 'Vấn Đề Chất Lượng',
        PROGRESS_UPDATE: 'Cập Nhật Tiến Độ',
    },

    // Actions
    CREATE: 'Tạo Mới',
    EDIT: 'Chỉnh Sửa',
    DELETE: 'Xóa',
    SAVE: 'Lưu',
    CANCEL: 'Hủy',
    APPROVE: 'Phê Duyệt',
    REJECT: 'Từ Chối',
    SUBMIT: 'Gửi',
    CONFIRM: 'Xác Nhận',
    CLOSE: 'Đóng',
    VIEW: 'Xem',
    DOWNLOAD: 'Tải Xuống',
    UPLOAD: 'Tải Lên',
    EXPORT: 'Xuất',
    IMPORT: 'Nhập',
    FILTER: 'Lọc',
    SORT: 'Sắp Xếp',
    REFRESH: 'Làm Mới',
    BACK: 'Quay Lại',
    NEXT: 'Tiếp Theo',
    PREVIOUS: 'Trước',
    FINISH: 'Hoàn Thành',

    // Status
    PENDING: 'Chờ Xử Lý',
    APPROVED: 'Đã Phê Duyệt',
    REJECTED: 'Đã Từ Chối',
    COMPLETED: 'Hoàn Thành',
    IN_PROGRESS: 'Đang Thực Hiện',
    DRAFT: 'Bản Nháp',
    SCHEDULED: 'Đã Lên Lịch',
    ACTIVE: 'Hoạt Động',
    INACTIVE: 'Không Hoạt Động',
    CANCELLED: 'Đã Hủy',
    OVERDUE: 'Quá Hạn',

    // Evidence
    EVIDENCE: {
        STAGE_BEFORE: 'Trước Thi Công',
        STAGE_DURING: 'Trong Thi Công',
        STAGE_AFTER: 'Sau Thi Công',
        UPLOAD_DATE: 'Ngày Tải Lên',
        UPLOADED_BY: 'Người Tải Lên',
        QUALITY_SCORE: 'Điểm Chất Lượng',
        GPS_LOCATION: 'Vị Trí GPS',
        FEEDBACK: 'Phản Hồi',
        BATCH_APPROVE: 'Phê Duyệt Hàng Loạt',
    },

    // Project
    PROJECT: {
        CODE: 'Mã Dự Án',
        NAME: 'Tên Dự Án',
        CUSTOMER: 'Khách Hàng',
        CONTRACT: 'Hợp Đồng',
        TYPE: 'Loại Dự Án',
        TYPE_INTERNAL: 'Nội Bộ',
        TYPE_OUTSOURCE: 'Outsource',
        ADDRESS: 'Địa Chỉ',
        GPS_COORDINATES: 'Tọa Độ GPS',
        START_DATE: 'Ngày Bắt Đầu',
        END_DATE: 'Ngày Kết Thúc',
        PROGRESS: 'Tiến Độ',
        STATUS: 'Trạng Thái',
        QUALITY_SCORE: 'Điểm Chất Lượng',
        OUTSOURCE_COMPANY: 'Công Ty Outsource',
        OUTSOURCE_LEADER: 'Trưởng Nhóm Outsource',
        SUPERVISOR: 'Giám Sát Viên',
        PM: 'Quản Lý Dự Án',
    },

    // User
    USER: {
        USERNAME: 'Tên Đăng Nhập',
        EMAIL: 'Email',
        FULL_NAME: 'Họ Và Tên',
        PHONE: 'Số Điện Thoại',
        ROLE: 'Vai Trò',
        DEPARTMENT: 'Phòng Ban',
        STATUS: 'Trạng Thái',
        LAST_LOGIN: 'Đăng Nhập Lần Cuối',
    },

    // Financial
    FINANCIAL: {
        AMOUNT: 'Số Tiền',
        PERCENTAGE: 'Phần Trăm',
        DUE_DATE: 'Hạn Thanh Toán',
        PAID_DATE: 'Ngày Thanh Toán',
        MILESTONE_TYPE: 'Loại Mốc',
        DEPOSIT: 'Đặt Cọc',
        ADVANCE: 'Tạm Ứng',
        ACCEPTANCE: 'Nghiệm Thu',
        FINAL: 'Thanh Lý',
        REVENUE: 'Doanh Thu',
        EXPENSE: 'Chi Phí',
        PROFIT: 'Lợi Nhuận',
        LOSS: 'Lỗ',
    },

    // Common Fields
    CREATED_DATE: 'Ngày Tạo',
    UPDATED_DATE: 'Ngày Cập Nhật',
    CREATED_BY: 'Người Tạo',
    UPDATED_BY: 'Người Cập Nhật',
    DESCRIPTION: 'Mô Tả',
    NOTE: 'Ghi Chú',
    REASON: 'Lý Do',

    // Messages
    MESSAGES: {
        SUCCESS_SAVE: 'Lưu thành công',
        SUCCESS_DELETE: 'Xóa thành công',
        SUCCESS_APPROVE: 'Phê duyệt thành công',
        SUCCESS_REJECT: 'Từ chối thành công',
        ERROR_SAVE: 'Lỗi khi lưu',
        ERROR_DELETE: 'Lỗi khi xóa',
        CONFIRM_DELETE: 'Bạn có chắc chắn muốn xóa?',
        CONFIRM_APPROVE: 'Bạn có chắc chắn muốn phê duyệt?',
        CONFIRM_REJECT: 'Bạn có chắc chắn muốn từ chối?',
        REQUIRED_FIELD: 'Trường này là bắt buộc',
        INVALID_EMAIL: 'Email không hợp lệ',
        INVALID_PHONE: 'Số điện thoại không hợp lệ',
    },
};
