/**
 * Enum for property types in schemas.
 */
export enum PropTypeEnum {
    TEXT = "Text",
    NUMBER = "Number",
    DATETIME = "DateTime",
    TIMESPAN = "TimeSpan",
    BOOLEAN = "Boolean",
    OBJECT_ID = "ObjectId",
    OBJECT_IDS = "ObjectIds",
    LOOKUP = "Lookup",
    LOOKUPS = "Lookups",
    LOOKUP_LOCAL_FIELD = "LookupLocalField",
    REFERENCE = "Reference",
    OBJECT = "Object",
    NESTED = "Nested",
    TAGS = "Tags",
    FILE_UPLOADS = "FileUploads",
    CUSTOM_COMPONENT = "CustomComponent",
    UI = "UI",
    JSON = "Json",
    GEOLOCATION = "Geolocation",
    ASSETS = "Assets",
    HEADLESS_CONTENT = "HeadlessContent",
    NEST_HEADLESS_CONTENT = "NestHeadlessContent",
    HEADLESS_FIELD_VALUE = "HeadlessFieldValue",
    HEADLESS_FIELD_PICKER = "HeadlessFieldPicker",
    SELECTION = "Selection",
    REF_LIST_DATA = "RefListData",
    REF_CUSTOM_DATA = "RefCustomData",
    REF_TO_DATA = "RefToData",
    SYSTEM_FIELD_PICKER = "SystemFieldPicker",
    RUNTIME_LOAD = "RuntimeLoad",
    FORM_GROUP_TEMPLATE = "FormGroupTemplate",
    FORM_GROUP_DATA = "FormGroupData",
    FORM_GROUP_MAPPING = "FormGroupMapping",
    APPROVAL_SNAPSHOT = "ApprovalSnapshot",
    DIRECTORY_TREE_REF = "DirectoryTreeRef",
    DATASOURCE_FILTER_REF = "DatasourceFilterRef",
    USER_GROUP_REFS = "UserGroupRefs",
    LINKED_AUTHORIZED_USER = "LinkedAuthorizedUser",
    AUTHORIZED_USER = "AuthorizedUser",
    AUTHORIZED_USERS = "AuthorizedUsers",
    RUNTIME_LOOKUP = "RuntimeLookup"
}
