name: Deployment — Dev (Branch dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-docker-deploy.yml
    with:
      bootstrap_spec: 'deploy/portainer-container-bootstrap-dev.json'
      container_name: 'bac-group-dev' # Thay đổi tùy theo dự án
      # endpoint_id: '1' # Ghi đè endpoint của dev nếu khác endpoint mặc định hoặc lấy từ vars.PORTAINER_ENDPOINT_ID
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PORTAINER_API_TOKEN: ${{ secrets.PORTAINER_API_TOKEN }}
      PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
