name: Deployment — Main (Branch main)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-docker-deploy.yml
    with:
      bootstrap_spec: 'deploy/portainer-container-bootstrap-main.json'
      container_name: 'bac-group-main'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PORTAINER_API_TOKEN: ${{ secrets.PORTAINER_API_TOKEN }}
      PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
